[package]
name = "trident-tests"
version = "0.1.0"
description = "Trident fuzz tests for Solana Stablecoin Standard"
edition = "2021"

[dependencies]
borsh = "1.5"
rand = "0.8"

[dependencies.trident-fuzz]
version = "0.12"

[[bin]]
name = "fuzz_0"
path = "fuzz_0/test_fuzz.rs"
